---
name:                      "Molecule: Github actions pipeline"
on:
  schedule:
    - cron:                "0 21 * * *"
  push:
    branches:
      - develop
  pull_request:
    types:
      - main
      - master
env:
  ANSIBLE_FORCE_COLOR:     "1"
  PY_COLORS:               "1"
  PYTHON_VERSION:          "3.6"
  MOLECULE_VERSION:        "3.0.8"

jobs:
  molecule:
    name:     "Molecule: Job"
    runs-on:  ubuntu-18.04
    steps:
      - name: "Init: Run checkout@v2"
        uses: actions/checkout@v2
      - name: "Init: Install dependencies"
        run:  |
          docker pull quay.io/ansible/molecule:${{ env.MOLECULE_VERSION }}
          docker run -di --name molecule-container \
                      -v "$(pwd)":/tmp/$(basename "${PWD}"):ro \
                      -v /var/run/docker.sock:/var/run/docker.sock \
                      -w /tmp/$(basename "${PWD}") \
                      quay.io/ansible/molecule:${{ env.MOLECULE_VERSION }}
        working-directory: /tmp
      - name:              "Ansible: Lint role"
        uses:              ansible/ansible-lint-action@master
        with:
          targets:         "./"
      - name: "Molecule: Create"
        run:  docker exec molecule-container molecule create
      - name: "Molecule: Converge"
        run:  docker exec molecule-container molecule converge
      - name: "Molecule: Idempotence"
        run:  docker exec molecule-container molecule idempotence
      - name: "Molecule: Verify"
        run:  docker exec molecule-container molecule verify
      - name: "Molecule: Destroy"
        run:  docker exec molecule-container molecule destroy
